# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aleksei/ClionProjects/RPK

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aleksei/ClionProjects/RPK

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aleksei/ClionProjects/RPK/CMakeFiles /home/aleksei/ClionProjects/RPK/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aleksei/ClionProjects/RPK/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

commons/Content.o: commons/Content.cpp.o
.PHONY : commons/Content.o

# target to build an object file
commons/Content.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/commons/Content.cpp.o
.PHONY : commons/Content.cpp.o

commons/Content.i: commons/Content.cpp.i
.PHONY : commons/Content.i

# target to preprocess a source file
commons/Content.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/commons/Content.cpp.i
.PHONY : commons/Content.cpp.i

commons/Content.s: commons/Content.cpp.s
.PHONY : commons/Content.s

# target to generate assembly for a file
commons/Content.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/commons/Content.cpp.s
.PHONY : commons/Content.cpp.s

commons/content_types/Content3D.o: commons/content_types/Content3D.cpp.o
.PHONY : commons/content_types/Content3D.o

# target to build an object file
commons/content_types/Content3D.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/commons/content_types/Content3D.cpp.o
.PHONY : commons/content_types/Content3D.cpp.o

commons/content_types/Content3D.i: commons/content_types/Content3D.cpp.i
.PHONY : commons/content_types/Content3D.i

# target to preprocess a source file
commons/content_types/Content3D.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/commons/content_types/Content3D.cpp.i
.PHONY : commons/content_types/Content3D.cpp.i

commons/content_types/Content3D.s: commons/content_types/Content3D.cpp.s
.PHONY : commons/content_types/Content3D.s

# target to generate assembly for a file
commons/content_types/Content3D.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/commons/content_types/Content3D.cpp.s
.PHONY : commons/content_types/Content3D.cpp.s

commons/content_types/FileContent.o: commons/content_types/FileContent.cpp.o
.PHONY : commons/content_types/FileContent.o

# target to build an object file
commons/content_types/FileContent.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/commons/content_types/FileContent.cpp.o
.PHONY : commons/content_types/FileContent.cpp.o

commons/content_types/FileContent.i: commons/content_types/FileContent.cpp.i
.PHONY : commons/content_types/FileContent.i

# target to preprocess a source file
commons/content_types/FileContent.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/commons/content_types/FileContent.cpp.i
.PHONY : commons/content_types/FileContent.cpp.i

commons/content_types/FileContent.s: commons/content_types/FileContent.cpp.s
.PHONY : commons/content_types/FileContent.s

# target to generate assembly for a file
commons/content_types/FileContent.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/commons/content_types/FileContent.cpp.s
.PHONY : commons/content_types/FileContent.cpp.s

lib/tinyxml2.o: lib/tinyxml2.cpp.o
.PHONY : lib/tinyxml2.o

# target to build an object file
lib/tinyxml2.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/lib/tinyxml2.cpp.o
.PHONY : lib/tinyxml2.cpp.o

lib/tinyxml2.i: lib/tinyxml2.cpp.i
.PHONY : lib/tinyxml2.i

# target to preprocess a source file
lib/tinyxml2.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/lib/tinyxml2.cpp.i
.PHONY : lib/tinyxml2.cpp.i

lib/tinyxml2.s: lib/tinyxml2.cpp.s
.PHONY : lib/tinyxml2.s

# target to generate assembly for a file
lib/tinyxml2.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/lib/tinyxml2.cpp.s
.PHONY : lib/tinyxml2.cpp.s

m_data_manager/compression/DMN_Compression.o: m_data_manager/compression/DMN_Compression.cpp.o
.PHONY : m_data_manager/compression/DMN_Compression.o

# target to build an object file
m_data_manager/compression/DMN_Compression.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/compression/DMN_Compression.cpp.o
.PHONY : m_data_manager/compression/DMN_Compression.cpp.o

m_data_manager/compression/DMN_Compression.i: m_data_manager/compression/DMN_Compression.cpp.i
.PHONY : m_data_manager/compression/DMN_Compression.i

# target to preprocess a source file
m_data_manager/compression/DMN_Compression.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/compression/DMN_Compression.cpp.i
.PHONY : m_data_manager/compression/DMN_Compression.cpp.i

m_data_manager/compression/DMN_Compression.s: m_data_manager/compression/DMN_Compression.cpp.s
.PHONY : m_data_manager/compression/DMN_Compression.s

# target to generate assembly for a file
m_data_manager/compression/DMN_Compression.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/compression/DMN_Compression.cpp.s
.PHONY : m_data_manager/compression/DMN_Compression.cpp.s

m_data_manager/compression/DMN_Compressor.o: m_data_manager/compression/DMN_Compressor.cpp.o
.PHONY : m_data_manager/compression/DMN_Compressor.o

# target to build an object file
m_data_manager/compression/DMN_Compressor.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/compression/DMN_Compressor.cpp.o
.PHONY : m_data_manager/compression/DMN_Compressor.cpp.o

m_data_manager/compression/DMN_Compressor.i: m_data_manager/compression/DMN_Compressor.cpp.i
.PHONY : m_data_manager/compression/DMN_Compressor.i

# target to preprocess a source file
m_data_manager/compression/DMN_Compressor.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/compression/DMN_Compressor.cpp.i
.PHONY : m_data_manager/compression/DMN_Compressor.cpp.i

m_data_manager/compression/DMN_Compressor.s: m_data_manager/compression/DMN_Compressor.cpp.s
.PHONY : m_data_manager/compression/DMN_Compressor.s

# target to generate assembly for a file
m_data_manager/compression/DMN_Compressor.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/compression/DMN_Compressor.cpp.s
.PHONY : m_data_manager/compression/DMN_Compressor.cpp.s

m_data_manager/compression/compression_types/DMN_3DCompression.o: m_data_manager/compression/compression_types/DMN_3DCompression.cpp.o
.PHONY : m_data_manager/compression/compression_types/DMN_3DCompression.o

# target to build an object file
m_data_manager/compression/compression_types/DMN_3DCompression.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/compression/compression_types/DMN_3DCompression.cpp.o
.PHONY : m_data_manager/compression/compression_types/DMN_3DCompression.cpp.o

m_data_manager/compression/compression_types/DMN_3DCompression.i: m_data_manager/compression/compression_types/DMN_3DCompression.cpp.i
.PHONY : m_data_manager/compression/compression_types/DMN_3DCompression.i

# target to preprocess a source file
m_data_manager/compression/compression_types/DMN_3DCompression.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/compression/compression_types/DMN_3DCompression.cpp.i
.PHONY : m_data_manager/compression/compression_types/DMN_3DCompression.cpp.i

m_data_manager/compression/compression_types/DMN_3DCompression.s: m_data_manager/compression/compression_types/DMN_3DCompression.cpp.s
.PHONY : m_data_manager/compression/compression_types/DMN_3DCompression.s

# target to generate assembly for a file
m_data_manager/compression/compression_types/DMN_3DCompression.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/compression/compression_types/DMN_3DCompression.cpp.s
.PHONY : m_data_manager/compression/compression_types/DMN_3DCompression.cpp.s

m_data_manager/compression/compression_types/DMN_ZipCompression.o: m_data_manager/compression/compression_types/DMN_ZipCompression.cpp.o
.PHONY : m_data_manager/compression/compression_types/DMN_ZipCompression.o

# target to build an object file
m_data_manager/compression/compression_types/DMN_ZipCompression.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/compression/compression_types/DMN_ZipCompression.cpp.o
.PHONY : m_data_manager/compression/compression_types/DMN_ZipCompression.cpp.o

m_data_manager/compression/compression_types/DMN_ZipCompression.i: m_data_manager/compression/compression_types/DMN_ZipCompression.cpp.i
.PHONY : m_data_manager/compression/compression_types/DMN_ZipCompression.i

# target to preprocess a source file
m_data_manager/compression/compression_types/DMN_ZipCompression.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/compression/compression_types/DMN_ZipCompression.cpp.i
.PHONY : m_data_manager/compression/compression_types/DMN_ZipCompression.cpp.i

m_data_manager/compression/compression_types/DMN_ZipCompression.s: m_data_manager/compression/compression_types/DMN_ZipCompression.cpp.s
.PHONY : m_data_manager/compression/compression_types/DMN_ZipCompression.s

# target to generate assembly for a file
m_data_manager/compression/compression_types/DMN_ZipCompression.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/compression/compression_types/DMN_ZipCompression.cpp.s
.PHONY : m_data_manager/compression/compression_types/DMN_ZipCompression.cpp.s

m_data_manager/cryptography/DMN_Cryptography.o: m_data_manager/cryptography/DMN_Cryptography.cpp.o
.PHONY : m_data_manager/cryptography/DMN_Cryptography.o

# target to build an object file
m_data_manager/cryptography/DMN_Cryptography.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/cryptography/DMN_Cryptography.cpp.o
.PHONY : m_data_manager/cryptography/DMN_Cryptography.cpp.o

m_data_manager/cryptography/DMN_Cryptography.i: m_data_manager/cryptography/DMN_Cryptography.cpp.i
.PHONY : m_data_manager/cryptography/DMN_Cryptography.i

# target to preprocess a source file
m_data_manager/cryptography/DMN_Cryptography.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/cryptography/DMN_Cryptography.cpp.i
.PHONY : m_data_manager/cryptography/DMN_Cryptography.cpp.i

m_data_manager/cryptography/DMN_Cryptography.s: m_data_manager/cryptography/DMN_Cryptography.cpp.s
.PHONY : m_data_manager/cryptography/DMN_Cryptography.s

# target to generate assembly for a file
m_data_manager/cryptography/DMN_Cryptography.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/cryptography/DMN_Cryptography.cpp.s
.PHONY : m_data_manager/cryptography/DMN_Cryptography.cpp.s

m_data_manager/data_manager/DMN_DataManager.o: m_data_manager/data_manager/DMN_DataManager.cpp.o
.PHONY : m_data_manager/data_manager/DMN_DataManager.o

# target to build an object file
m_data_manager/data_manager/DMN_DataManager.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/DMN_DataManager.cpp.o
.PHONY : m_data_manager/data_manager/DMN_DataManager.cpp.o

m_data_manager/data_manager/DMN_DataManager.i: m_data_manager/data_manager/DMN_DataManager.cpp.i
.PHONY : m_data_manager/data_manager/DMN_DataManager.i

# target to preprocess a source file
m_data_manager/data_manager/DMN_DataManager.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/DMN_DataManager.cpp.i
.PHONY : m_data_manager/data_manager/DMN_DataManager.cpp.i

m_data_manager/data_manager/DMN_DataManager.s: m_data_manager/data_manager/DMN_DataManager.cpp.s
.PHONY : m_data_manager/data_manager/DMN_DataManager.s

# target to generate assembly for a file
m_data_manager/data_manager/DMN_DataManager.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/DMN_DataManager.cpp.s
.PHONY : m_data_manager/data_manager/DMN_DataManager.cpp.s

m_data_manager/data_manager/DMN_DataSource.o: m_data_manager/data_manager/DMN_DataSource.cpp.o
.PHONY : m_data_manager/data_manager/DMN_DataSource.o

# target to build an object file
m_data_manager/data_manager/DMN_DataSource.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/DMN_DataSource.cpp.o
.PHONY : m_data_manager/data_manager/DMN_DataSource.cpp.o

m_data_manager/data_manager/DMN_DataSource.i: m_data_manager/data_manager/DMN_DataSource.cpp.i
.PHONY : m_data_manager/data_manager/DMN_DataSource.i

# target to preprocess a source file
m_data_manager/data_manager/DMN_DataSource.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/DMN_DataSource.cpp.i
.PHONY : m_data_manager/data_manager/DMN_DataSource.cpp.i

m_data_manager/data_manager/DMN_DataSource.s: m_data_manager/data_manager/DMN_DataSource.cpp.s
.PHONY : m_data_manager/data_manager/DMN_DataSource.s

# target to generate assembly for a file
m_data_manager/data_manager/DMN_DataSource.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/DMN_DataSource.cpp.s
.PHONY : m_data_manager/data_manager/DMN_DataSource.cpp.s

m_data_manager/data_manager/DMN_DataSourceManager.o: m_data_manager/data_manager/DMN_DataSourceManager.cpp.o
.PHONY : m_data_manager/data_manager/DMN_DataSourceManager.o

# target to build an object file
m_data_manager/data_manager/DMN_DataSourceManager.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/DMN_DataSourceManager.cpp.o
.PHONY : m_data_manager/data_manager/DMN_DataSourceManager.cpp.o

m_data_manager/data_manager/DMN_DataSourceManager.i: m_data_manager/data_manager/DMN_DataSourceManager.cpp.i
.PHONY : m_data_manager/data_manager/DMN_DataSourceManager.i

# target to preprocess a source file
m_data_manager/data_manager/DMN_DataSourceManager.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/DMN_DataSourceManager.cpp.i
.PHONY : m_data_manager/data_manager/DMN_DataSourceManager.cpp.i

m_data_manager/data_manager/DMN_DataSourceManager.s: m_data_manager/data_manager/DMN_DataSourceManager.cpp.s
.PHONY : m_data_manager/data_manager/DMN_DataSourceManager.s

# target to generate assembly for a file
m_data_manager/data_manager/DMN_DataSourceManager.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/DMN_DataSourceManager.cpp.s
.PHONY : m_data_manager/data_manager/DMN_DataSourceManager.cpp.s

m_data_manager/data_manager/data_source/DMN_DataSource3D.o: m_data_manager/data_manager/data_source/DMN_DataSource3D.cpp.o
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSource3D.o

# target to build an object file
m_data_manager/data_manager/data_source/DMN_DataSource3D.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/data_source/DMN_DataSource3D.cpp.o
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSource3D.cpp.o

m_data_manager/data_manager/data_source/DMN_DataSource3D.i: m_data_manager/data_manager/data_source/DMN_DataSource3D.cpp.i
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSource3D.i

# target to preprocess a source file
m_data_manager/data_manager/data_source/DMN_DataSource3D.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/data_source/DMN_DataSource3D.cpp.i
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSource3D.cpp.i

m_data_manager/data_manager/data_source/DMN_DataSource3D.s: m_data_manager/data_manager/data_source/DMN_DataSource3D.cpp.s
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSource3D.s

# target to generate assembly for a file
m_data_manager/data_manager/data_source/DMN_DataSource3D.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/data_source/DMN_DataSource3D.cpp.s
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSource3D.cpp.s

m_data_manager/data_manager/data_source/DMN_DataSourceDB.o: m_data_manager/data_manager/data_source/DMN_DataSourceDB.cpp.o
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSourceDB.o

# target to build an object file
m_data_manager/data_manager/data_source/DMN_DataSourceDB.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/data_source/DMN_DataSourceDB.cpp.o
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSourceDB.cpp.o

m_data_manager/data_manager/data_source/DMN_DataSourceDB.i: m_data_manager/data_manager/data_source/DMN_DataSourceDB.cpp.i
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSourceDB.i

# target to preprocess a source file
m_data_manager/data_manager/data_source/DMN_DataSourceDB.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/data_source/DMN_DataSourceDB.cpp.i
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSourceDB.cpp.i

m_data_manager/data_manager/data_source/DMN_DataSourceDB.s: m_data_manager/data_manager/data_source/DMN_DataSourceDB.cpp.s
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSourceDB.s

# target to generate assembly for a file
m_data_manager/data_manager/data_source/DMN_DataSourceDB.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/data_source/DMN_DataSourceDB.cpp.s
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSourceDB.cpp.s

m_data_manager/data_manager/data_source/DMN_DataSourceFile.o: m_data_manager/data_manager/data_source/DMN_DataSourceFile.cpp.o
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSourceFile.o

# target to build an object file
m_data_manager/data_manager/data_source/DMN_DataSourceFile.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/data_source/DMN_DataSourceFile.cpp.o
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSourceFile.cpp.o

m_data_manager/data_manager/data_source/DMN_DataSourceFile.i: m_data_manager/data_manager/data_source/DMN_DataSourceFile.cpp.i
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSourceFile.i

# target to preprocess a source file
m_data_manager/data_manager/data_source/DMN_DataSourceFile.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/data_source/DMN_DataSourceFile.cpp.i
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSourceFile.cpp.i

m_data_manager/data_manager/data_source/DMN_DataSourceFile.s: m_data_manager/data_manager/data_source/DMN_DataSourceFile.cpp.s
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSourceFile.s

# target to generate assembly for a file
m_data_manager/data_manager/data_source/DMN_DataSourceFile.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/data_manager/data_source/DMN_DataSourceFile.cpp.s
.PHONY : m_data_manager/data_manager/data_source/DMN_DataSourceFile.cpp.s

m_data_manager/updater/DMN_ContentUpdate.o: m_data_manager/updater/DMN_ContentUpdate.cpp.o
.PHONY : m_data_manager/updater/DMN_ContentUpdate.o

# target to build an object file
m_data_manager/updater/DMN_ContentUpdate.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/updater/DMN_ContentUpdate.cpp.o
.PHONY : m_data_manager/updater/DMN_ContentUpdate.cpp.o

m_data_manager/updater/DMN_ContentUpdate.i: m_data_manager/updater/DMN_ContentUpdate.cpp.i
.PHONY : m_data_manager/updater/DMN_ContentUpdate.i

# target to preprocess a source file
m_data_manager/updater/DMN_ContentUpdate.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/updater/DMN_ContentUpdate.cpp.i
.PHONY : m_data_manager/updater/DMN_ContentUpdate.cpp.i

m_data_manager/updater/DMN_ContentUpdate.s: m_data_manager/updater/DMN_ContentUpdate.cpp.s
.PHONY : m_data_manager/updater/DMN_ContentUpdate.s

# target to generate assembly for a file
m_data_manager/updater/DMN_ContentUpdate.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_data_manager/updater/DMN_ContentUpdate.cpp.s
.PHONY : m_data_manager/updater/DMN_ContentUpdate.cpp.s

m_security/SCR_AccessManager.o: m_security/SCR_AccessManager.cpp.o
.PHONY : m_security/SCR_AccessManager.o

# target to build an object file
m_security/SCR_AccessManager.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_security/SCR_AccessManager.cpp.o
.PHONY : m_security/SCR_AccessManager.cpp.o

m_security/SCR_AccessManager.i: m_security/SCR_AccessManager.cpp.i
.PHONY : m_security/SCR_AccessManager.i

# target to preprocess a source file
m_security/SCR_AccessManager.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_security/SCR_AccessManager.cpp.i
.PHONY : m_security/SCR_AccessManager.cpp.i

m_security/SCR_AccessManager.s: m_security/SCR_AccessManager.cpp.s
.PHONY : m_security/SCR_AccessManager.s

# target to generate assembly for a file
m_security/SCR_AccessManager.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/m_security/SCR_AccessManager.cpp.s
.PHONY : m_security/SCR_AccessManager.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

settings/Settings.o: settings/Settings.cpp.o
.PHONY : settings/Settings.o

# target to build an object file
settings/Settings.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/settings/Settings.cpp.o
.PHONY : settings/Settings.cpp.o

settings/Settings.i: settings/Settings.cpp.i
.PHONY : settings/Settings.i

# target to preprocess a source file
settings/Settings.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/settings/Settings.cpp.i
.PHONY : settings/Settings.cpp.i

settings/Settings.s: settings/Settings.cpp.s
.PHONY : settings/Settings.s

# target to generate assembly for a file
settings/Settings.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/settings/Settings.cpp.s
.PHONY : settings/Settings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... rebuild_cache"
	@echo "... commons/Content.o"
	@echo "... commons/Content.i"
	@echo "... commons/Content.s"
	@echo "... commons/content_types/Content3D.o"
	@echo "... commons/content_types/Content3D.i"
	@echo "... commons/content_types/Content3D.s"
	@echo "... commons/content_types/FileContent.o"
	@echo "... commons/content_types/FileContent.i"
	@echo "... commons/content_types/FileContent.s"
	@echo "... lib/tinyxml2.o"
	@echo "... lib/tinyxml2.i"
	@echo "... lib/tinyxml2.s"
	@echo "... m_data_manager/compression/DMN_Compression.o"
	@echo "... m_data_manager/compression/DMN_Compression.i"
	@echo "... m_data_manager/compression/DMN_Compression.s"
	@echo "... m_data_manager/compression/DMN_Compressor.o"
	@echo "... m_data_manager/compression/DMN_Compressor.i"
	@echo "... m_data_manager/compression/DMN_Compressor.s"
	@echo "... m_data_manager/compression/compression_types/DMN_3DCompression.o"
	@echo "... m_data_manager/compression/compression_types/DMN_3DCompression.i"
	@echo "... m_data_manager/compression/compression_types/DMN_3DCompression.s"
	@echo "... m_data_manager/compression/compression_types/DMN_ZipCompression.o"
	@echo "... m_data_manager/compression/compression_types/DMN_ZipCompression.i"
	@echo "... m_data_manager/compression/compression_types/DMN_ZipCompression.s"
	@echo "... m_data_manager/cryptography/DMN_Cryptography.o"
	@echo "... m_data_manager/cryptography/DMN_Cryptography.i"
	@echo "... m_data_manager/cryptography/DMN_Cryptography.s"
	@echo "... m_data_manager/data_manager/DMN_DataManager.o"
	@echo "... m_data_manager/data_manager/DMN_DataManager.i"
	@echo "... m_data_manager/data_manager/DMN_DataManager.s"
	@echo "... m_data_manager/data_manager/DMN_DataSource.o"
	@echo "... m_data_manager/data_manager/DMN_DataSource.i"
	@echo "... m_data_manager/data_manager/DMN_DataSource.s"
	@echo "... m_data_manager/data_manager/DMN_DataSourceManager.o"
	@echo "... m_data_manager/data_manager/DMN_DataSourceManager.i"
	@echo "... m_data_manager/data_manager/DMN_DataSourceManager.s"
	@echo "... m_data_manager/data_manager/data_source/DMN_DataSource3D.o"
	@echo "... m_data_manager/data_manager/data_source/DMN_DataSource3D.i"
	@echo "... m_data_manager/data_manager/data_source/DMN_DataSource3D.s"
	@echo "... m_data_manager/data_manager/data_source/DMN_DataSourceDB.o"
	@echo "... m_data_manager/data_manager/data_source/DMN_DataSourceDB.i"
	@echo "... m_data_manager/data_manager/data_source/DMN_DataSourceDB.s"
	@echo "... m_data_manager/data_manager/data_source/DMN_DataSourceFile.o"
	@echo "... m_data_manager/data_manager/data_source/DMN_DataSourceFile.i"
	@echo "... m_data_manager/data_manager/data_source/DMN_DataSourceFile.s"
	@echo "... m_data_manager/updater/DMN_ContentUpdate.o"
	@echo "... m_data_manager/updater/DMN_ContentUpdate.i"
	@echo "... m_data_manager/updater/DMN_ContentUpdate.s"
	@echo "... m_security/SCR_AccessManager.o"
	@echo "... m_security/SCR_AccessManager.i"
	@echo "... m_security/SCR_AccessManager.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... settings/Settings.o"
	@echo "... settings/Settings.i"
	@echo "... settings/Settings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

